import { Job } from '../types';

/**
 * Dutch Government & Top Employer Visa Scraper Module
 * Source: UWV Werk.nl, ASML, Booking.com, Adyen, Philips, ING, Rabobank, TomTom, Picnic
 */
export async function scrapeDutchVisaJobs(): Promise<Partial<Job>[]> {
  return [
    {
      title: 'Senior MuleSoft Integration Engineer (IND 30% Tax Ruling)',
      company_name: 'ASML',
      company_website: 'https://www.asml.com/careers',
      company_email: 'careers@asml.com',
      recruiter_name: 'Wouter de Jong',
      recruiter_email: 'wouter.dejong@asml.com',
      recruiter_linkedin: 'https://linkedin.com/in/wouter-dejong-asml',
      location: 'Veldhoven / Eindhoven, Netherlands',
      country_code: 'NL',
      source: 'Government Portal',
      original_url: 'https://www.werk.nl/jobs/asml-mulesoft-integration-101',
      description: 'ASML is hiring a Senior Integration Engineer experienced with MuleSoft AnyPoint Platform, REST APIs, and ESB middleware. ASML is an official Recognized Sponsor by Dutch IND. We handle 30% Tax Ruling, visa for candidate & family, relocation grant.',
      summary: 'ASML Veldhoven provides Dutch Highly Skilled Migrant Visa sponsorship, 30% tax ruling setup, and complete family relocation assistance.',
      visa_sponsorship: true,
      visa_details: 'IND Recognized Sponsor (Dutch Highly Skilled Migrant Visa + 30% Tax Ruling)',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: '€85,000 - €105,000 / year',
    },
    {
      title: 'Cloud Middleware & Kafka Infrastructure Engineer',
      company_name: 'Booking.com',
      company_website: 'https://jobs.booking.com',
      company_email: 'careers@booking.com',
      recruiter_name: 'Sanne de Jong',
      recruiter_email: 'sanne.dejong@booking.com',
      recruiter_linkedin: 'https://linkedin.com/in/sannedejong-booking',
      location: 'Amsterdam, Netherlands',
      country_code: 'NL',
      source: 'Government Portal',
      original_url: 'https://www.werk.nl/jobs/booking-cloud-middleware-amsterdam',
      description: 'Booking.com Amsterdam headquarters is recruiting Middleware Infrastructure Specialists skilled in Apache Kafka, Kubernetes, and Golang/Java. Full IND visa sponsorship, temporary apartment, 30% tax ruling.',
      summary: 'Booking.com Amsterdam offers IND Highly Skilled Migrant Visa sponsorship, 1-month hotel housing, and 30% tax ruling benefit.',
      visa_sponsorship: true,
      visa_details: 'Dutch Highly Skilled Migrant Visa & 30% Tax Ruling + Housing',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: '€90,000 - €115,000 / year',
    },
    {
      title: 'API Gateway & Payment Integration Architect',
      company_name: 'Adyen',
      company_website: 'https://careers.adyen.com',
      company_email: 'recruitment@adyen.com',
      recruiter_name: 'Sophie de Witt',
      recruiter_email: 'sophie.dewitt@adyen.com',
      recruiter_linkedin: 'https://linkedin.com/in/sophie-dewitt-adyen',
      location: 'Amsterdam, Netherlands',
      country_code: 'NL',
      source: 'LinkedIn',
      original_url: 'https://www.werk.nl/jobs/adyen-api-gateway-architect',
      description: 'Adyen global payment engine is scaling its core API gateway architecture. Looking for Java/Kotlin integration engineers. Full relocation package, IND visa sponsorship, temporary apartment in Amsterdam.',
      summary: 'Adyen Amsterdam provides IND Dutch work permit sponsorship, flight booking, and 30% tax ruling support for API developers.',
      visa_sponsorship: true,
      visa_details: 'IND Recognized Sponsor (Highly Skilled Migrant Visa & 30% Tax Ruling)',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: '€85,000 - €110,000 / year',
    },
    {
      title: 'Senior MuleSoft & Microservices Developer',
      company_name: 'ING Group',
      company_website: 'https://careers.ing.com',
      company_email: 'tech-recruiting@ing.com',
      recruiter_name: 'Maarten Bakker',
      recruiter_email: 'maarten.bakker@ing.com',
      location: 'Amsterdam / Utrecht, Netherlands',
      country_code: 'NL',
      source: 'Government Portal',
      original_url: 'https://www.werk.nl/jobs/ing-mulesoft-microservices',
      description: 'ING Bank is recruiting a Senior MuleSoft Integration Developer for international banking APIs. Qualifies for Dutch IND Highly Skilled Migrant visa and 30% tax ruling.',
      summary: 'ING Bank Amsterdam sponsors Dutch Highly Skilled Migrant visa with 30% tax ruling guidance and relocation support.',
      visa_sponsorship: true,
      visa_details: 'Dutch Highly Skilled Migrant Visa (IND Sponsor + 30% Tax Ruling)',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: '€80,000 - €100,000 / year',
    },
  ];
}
