import { Job } from '../types';

/**
 * Nordic Government & Top Employer Visa Scraper Module
 * Source: Workindenmark, Arbetsförmedlingen, Novo Nordisk, Spotify, Ericsson, Volvo, Klarna, Nokia, KONE
 */
export async function scrapeNordicVisaJobs(): Promise<Partial<Job>[]> {
  return [
    {
      title: 'Senior Clinical & Health Data Integration Lead',
      company_name: 'Novo Nordisk',
      company_website: 'https://www.novonordisk.com/careers.html',
      company_email: 'pharma-careers@novonordisk.com',
      recruiter_name: 'Mette Nielsen',
      recruiter_email: 'mette.nielsen@novonordisk.com',
      recruiter_linkedin: 'https://linkedin.com/in/mettenielsen-novo',
      location: 'Copenhagen / Bagsværd, Denmark',
      country_code: 'DK',
      source: 'Government Portal',
      original_url: 'https://www.workindenmark.dk/jobs/novo-nordisk-data-integration',
      description: 'Novo Nordisk global headquarters is hiring a Clinical Data Integration Lead. Sponsoring Danish Pay Limit Scheme work permit with fast-track visa clearance, relocation agency assistance, and flight tickets.',
      summary: 'Novo Nordisk Copenhagen provides Danish Pay Limit Scheme visa sponsorship, flight booking, and relocation agency support.',
      visa_sponsorship: true,
      visa_details: 'Official Danish Pay Limit Scheme Work Permit Sponsorship + Relocation Service',
      category: 'Healthcare',
      job_type: 'Full-time',
      salary_range: 'DKK 700,000 - DKK 900,000 / year',
    },
    {
      title: 'Senior Cloud Integration & MuleSoft Engineer',
      company_name: 'Spotify',
      company_website: 'https://www.lifeatspotify.com/jobs',
      company_email: 'recruitment@spotify.com',
      recruiter_name: 'Elin Lindqvist',
      recruiter_email: 'elin.l@spotify.com',
      recruiter_linkedin: 'https://linkedin.com/in/elinlindqvist-spotify',
      location: 'Stockholm, Sweden (Hybrid)',
      country_code: 'SE',
      source: 'Government Portal',
      original_url: 'https://arbetsformedlingen.se/jobs/spotify-cloud-integration-stockholm',
      description: 'Spotify is seeking a Senior Integration Engineer to connect enterprise financial backend services and APIs. Swedish work permit visa sponsorship, relocation service, and equity RSU package included.',
      summary: 'Spotify Stockholm offers Swedish work permit sponsorship, relocation support, and equity stock grants.',
      visa_sponsorship: true,
      visa_details: 'Swedish Work Permit Sponsorship & Full Relocation Service',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: 'SEK 850,000 - SEK 1,100,000 / year',
    },
    {
      title: 'Global 5G Core Network & Middleware Architect',
      company_name: 'Ericsson',
      company_website: 'https://www.ericsson.com/careers',
      company_email: 'careers@ericsson.com',
      recruiter_name: 'Johan Svensson',
      recruiter_email: 'johan.svensson@ericsson.com',
      location: 'Stockholm / Kista, Sweden',
      country_code: 'SE',
      source: 'Government Portal',
      original_url: 'https://arbetsformedlingen.se/jobs/ericsson-5g-middleware-kista',
      description: 'Ericsson headquarters in Kista is recruiting 5G Middleware Architects. Swedish work permit sponsorship and relocation assistance for non-EU engineering candidates.',
      summary: 'Ericsson Stockholm provides Swedish work permit visa sponsorship and relocation support.',
      visa_sponsorship: true,
      visa_details: 'Swedish Work Permit Visa Sponsorship',
      category: 'Engineering',
      job_type: 'Full-time',
      salary_range: 'SEK 800,000 - SEK 1,000,000 / year',
    },
    {
      title: '5G Cloud Systems & Cloud Native Developer',
      company_name: 'Nokia',
      company_website: 'https://www.nokia.com/about-us/careers',
      company_email: 'careers@nokia.com',
      recruiter_name: 'Jari Virtanen',
      recruiter_email: 'jari.virtanen@nokia.com',
      location: 'Espoo / Helsinki, Finland',
      country_code: 'FI',
      source: 'Government Portal',
      original_url: 'https://tyomarkkinatori.fi/jobs/nokia-cloud-native-espoo',
      description: 'Nokia Espoo is hiring Cloud Native Developers for 5G core network products. Sponsoring Finnish Specialist Residence Permit with fast-track processing within 2 weeks.',
      summary: 'Nokia Finland sponsors Finnish Specialist Residence Permit with fast-track 14-day visa processing and relocation allowance.',
      visa_sponsorship: true,
      visa_details: 'Finnish Specialist Residence Permit (Fast-Track 14 Days)',
      category: 'Software Engineering',
      job_type: 'Full-time',
      salary_range: '€70,000 - €90,000 / year',
    },
  ];
}
